config/routes.rb
Rails.application.routes.draw do
  resources :classrooms
  resources :courses
  resources :students

  root 'students#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student
  belongs_to :course

  validates :student_id, presence: true
  validates :course_id, presence: true

  before_create {self.entry_at = DateTime.now }
end

app/models/course.rb
class Course < ActiveRecord::Base
  extend EnumerateIt

  has_many :classrooms
  has_many :students, :through => :classrooms

  has_enumeration_for :status, with: ActiveStatus

  validates :name, presence: true, length: {maximum: 45}
  validates :description, presence: true, length: {maximum: 45}
  validates :status, presence: true

  before_validation {self.status = self.status.to_i}
end

app/models/student.rb
class Student < ActiveRecord::Base
  extend EnumerateIt

  has_many :classrooms
  has_many :courses, :through => :classrooms

  has_enumeration_for :status, with: ActiveStatus

  validates :name, presence: true, length: {maximum: 45}
  validates :register_number, presence: true, length: {maximum: 45}
  validates :status, presence: true

  before_validation {self.status = self.status.to_i}
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @classrooms = Classroom.all
    respond_with(@classrooms)
  end

  def show
    respond_with(@classroom)
  end

  def new
    @students = Student.all
    @courses = Course.all
    @classroom = Classroom.new
    respond_with(@classroom)
  end

  def edit
    @students = Student.all
    @courses = Course.all
  end

  def create
    @classroom = Classroom.new(classroom_params)
    @classroom.save
    respond_with(@classroom)
  end

  def update
    @classroom.update(classroom_params)
    respond_with(@classroom)
  end

  def destroy
    @classroom.destroy
    respond_with(@classroom)
  end

  private
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    def classroom_params
      params.require(:classroom).permit(:student_id, :course_id, :entry_at)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @courses = Course.all
    respond_with(@courses)
  end

  def show
    respond_with(@course)
  end

  def new
    @course = Course.new
    respond_with(@course)
  end

  def edit
  end

  def create
    @course = Course.new(course_params)
    @course.save
    respond_with(@course)
  end

  def update
    @course.update(course_params)
    respond_with(@course)
  end

  def destroy
    @course.destroy
    respond_with(@course)
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :description, :status)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @students = Student.all
    respond_with(@students)
  end

  def show
    respond_with(@student)
  end

  def new
    @student = Student.new
    respond_with(@student)
  end

  def edit
  end

  def create
    @student = Student.new(student_params)
    @student.save
    respond_with(@student)
  end

  def update
    @student.update(student_params)
    respond_with(@student)
  end

  def destroy
    @student.destroy
    respond_with(@student)
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name, :register_number, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/classrooms/_form.html.slim
= form_for @classroom do |f|
  - if @classroom.errors.any?
    #error_explanation
      h2 = t('errors.template.header', model: t('activerecord.models.classroom.one'), count: @classroom.errors.count)
      ul
        - @classroom.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :student
    = f.select :student_id, @students.collect {|student| [ "#{student.name} - #{student.register_number}", student.id ]}
  .field
    = f.label :course
    = f.select :course_id, @courses.collect {|course| [ course.name, course.id ]}
  /.field
  /  = f.label :entry_at
  /  = f.datetime_select :entry_at
  .actions = f.submit

app/views/classrooms/edit.html.slim
h1 = t('editing', resource: t('activerecord.models.classroom.one'))

== render 'form'

= link_to t('show'), @classroom
'  |
= link_to t('back'), classrooms_path

app/views/classrooms/index.html.slim
h1 = t('listing', resource: t('activerecord.models.classroom.other'))

table
  thead
    tr
      th = t('activerecord.attributes.classroom.student')
      th = t('activerecord.attributes.classroom.course')
      th = t('activerecord.attributes.classroom.entry_at')
      th
      th
      th

  tbody
    - @classrooms.each do |classroom|
      tr
        td = "#{classroom.student.name} - #{classroom.student.register_number}"
        td = classroom.course.name
        td = classroom.entry_at
        td = link_to t('show'), classroom
        td = link_to t('edit'), edit_classroom_path(classroom)
        td = link_to t('destroy'), classroom, data: { confirm: t('are_you_sure') }, method: :delete

br

= link_to t('create_new', resource: t('activerecord.models.classroom.one')), new_classroom_path
br
= link_to t('activerecord.models.student.other'), students_path
br
= link_to t('activerecord.models.course.other'), courses_path

app/views/classrooms/new.html.slim
h1 = t('create_new', resource: t('activerecord.models.classroom.one'))

== render 'form'

= link_to t('back'), classrooms_path

app/views/classrooms/show.html.slim
p#notice = notice

p
  strong = "#{t('activerecord.attributes.classroom.student')}:"
  = "#{@classroom.student.name} - #{@classroom.student.register_number}"
p
  strong = "#{t('activerecord.attributes.classroom.course')}:"
  = @classroom.course.name
p
  strong = "#{t('activerecord.attributes.classroom.entry_at')}:"
  = @classroom.entry_at

= link_to t('edit'), edit_classroom_path(@classroom)
'  |
= link_to t('back'), classrooms_path

app/views/courses/_form.html.slim
= form_for @course do |f|
  - if @course.errors.any?
    #error_explanation
      h2 = t('errors.template.header', model: t('activerecord.models.course.one'), count: @course.errors.count)
      ul
        - @course.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :status
    = f.select :status, @course.class.enumerations[:status].to_a
  .actions = f.submit

app/views/courses/edit.html.slim
h1 = t('editing', resource: t('activerecord.models.course.one'))

== render 'form'

= link_to t('show'), @course
'  |
= link_to t('back'), courses_path

app/views/courses/index.html.slim
h1 = t('listing', resource: t('activerecord.models.course.one'))

table
  thead
    tr
      th = t('activerecord.attributes.course.name')
      th = t('activerecord.attributes.course.description')
      th = t('activerecord.attributes.course.status')
      th
      th
      th

  tbody
    - @courses.each do |course|
      tr
        td = course.name
        td = course.description
        td = course.status_humanize
        td = link_to t('show'), course
        td = link_to t('edit'), edit_course_path(course)
        td = link_to t('destroy'), course, data: { confirm: t('are_you_sure') }, method: :delete

br

= link_to t('create_new', resource: t('activerecord.models.course.one')), new_course_path
br
= link_to t('activerecord.models.student.other'), students_path
br
= link_to t('activerecord.models.classroom.other'), classrooms_path

app/views/courses/new.html.slim
h1 = t('create_new', resource: t('activerecord.models.course.one'))

== render 'form'

= link_to t('back'), courses_path

app/views/courses/show.html.slim
p#notice = notice

p
  strong = "#{t('activerecord.attributes.course.name')}:"
  = @course.name
p
  strong = "#{t('activerecord.attributes.course.description')}:"
  = @course.description
p
  strong = "#{t('activerecord.attributes.course.status')}:"
  = @course.status_humanize

= link_to t('edit'), edit_course_path(@course)
'  |
= link_to t('back'), courses_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>University</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.slim
= form_for @student do |f|
  - if @student.errors.any?
    #error_explanation
      h2 = t('errors.template.header', model: t('activerecord.models.student.one'), count: @student.errors.count)
      ul
        - @student.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :register_number
    = f.text_field :register_number
  .field
    = f.label :status
    = f.select :status, @student.class.enumerations[:status].to_a
  .actions = f.submit

app/views/students/edit.html.slim
h1 = t('editing', resource: t('activerecord.models.student.one'))

== render 'form'

= link_to t('show'), @student
'  |
= link_to t('back'), students_path

app/views/students/index.html.slim
h1 = t('listing', resource: t('activerecord.models.student.other'))

table
  thead
    tr
      th = t('activerecord.attributes.student.name')
      th = t('activerecord.attributes.student.register_number')
      th = t('activerecord.attributes.student.status')
      th
      th
      th

  tbody
    - @students.each do |student|
      tr
        td = student.name
        td = student.register_number
        td = student.status_humanize
        td = link_to t('show'), student
        td = link_to t('edit'), edit_student_path(student)
        td = link_to t('destroy'), student, data: { confirm: t('are_you_sure') }, method: :delete

br

= link_to t('create_new', resource: t('activerecord.models.student.one')), new_student_path
br
= link_to t('activerecord.models.classroom.other'), classrooms_path
br
= link_to t('activerecord.models.course.other'), courses_path

app/views/students/new.html.slim
h1 = t('create_new', resource: t('activerecord.models.student.one'))

== render 'form'

= link_to t('back'), students_path

app/views/students/show.html.slim
p#notice = notice

p
  strong = "#{t('activerecord.attributes.student.name')}:"
  = @student.name
p
  strong = "#{t('activerecord.attributes.student.register_number')}:"
  = @student.register_number
p
  strong = "#{t('activerecord.attributes.student.status')}:"
  = @student.status_humanize

= link_to t('edit'), edit_student_path(@student)
'  |
= link_to t('back'), students_path